### PR TITLE
[Polygon Edge] Remove seal flag + add missing flag to index

### PR DESCRIPTION
**Pull request by laviniat1996**

### CODE REVIEW

**Review by DannyS03 — CHANGES_REQUESTED** [review]
link format should be updated

**Review by Kourin1996 — APPROVED** [review]

**Review by zivkovicmilos — APPROVED** [review]

**Comment by zivkovicmilos** [comment]
@laviniat1996 

You should update this branch with the latest changes from `master`.

@DannyS03 
What link formats are you talking about?

**Comment by laviniat1996** [comment]
@DannyS03 what links format should be used?

**Comment by DannyS03** [comment]
Sorry missed this @zivkovicmilos @laviniat1996. To avoid a trailing slash issue we started adding ".md" to the end of the file name.

**Review by DannyS03 — APPROVED** [review]
To move this forward,  we'll include the link updates in a PR that updates to this format.

**Pull request merged**
