### PR TITLE
removed slugs

### PR DESCRIPTION
**Pull request by cerberushades**

### CODE REVIEW

**Review by DannyS03 — CHANGES_REQUESTED** [review]
some pages start the metadata on the second line and won't be recognized

**Review by DannyS03 — CHANGES_REQUESTED** [review]
introduction.md is missing metadata & while these docs will be updated again, many have extra spacing after the metadata

**Review by DannyS03 — COMMENTED** [review]
introduction.md is being accidentally deleted

**Comment by cerberushades** [comment]
> introduction.md is being accidentally deleted

it is supposed to be deleted. It is just an old version of the overview file

**Comment by DannyS03** [comment]
> > introduction.md is being accidentally deleted
> 
> it is supposed to be deleted. It is just an old version of the overview file @DannyS03

oh right, whoops

**Review by DannyS03 — APPROVED** [review]

**Pull request merged**
