### PR TITLE
Improves diagram resolution

### PR DESCRIPTION
**Pull request by cerberushades**

### CODE REVIEW

**Review by DannyS03 — CHANGES_REQUESTED** [review]
It is still unclear as the diagram itself is large

**Comment by DannyS03** [comment]
Would suggest (for now at least) that we create a custom version for the Wiki

**Comment by cerberushades** [comment]
> It is still unclear as the diagram itself is large

It is at least more readable.

**Comment by DannyS03** [comment]
Using to also test deployment.

**Pull request merged**
