### PR TITLE
feat(wiki): add tabs on the landing page for protocol docs

### PR DESCRIPTION
**Pull request by ashucoder9**

### CODE REVIEW

**Review by DannyS03 — CHANGES_REQUESTED** [review]
thanks @ashucoder9, looks solid! 

- It would probably look even better if the tab bar is compact, where it starts and ends at the first tab and last tab, respectively. This is similar to the main site tab bar:

image

- We can also include your idea of using buttons

**Comment by ashucoder9** [comment]
Thanks and yes, we need to fix the tab container.

**Comment by DannyS03** [comment]
Also for Avail and Supernets, we can change "coming soon" to "testnet".

**Review by DannyS03 — CHANGES_REQUESTED** [review]
thanks for the updates @ashucoder9

- Better if the tabs were compact rather than spread out with the same margins.
- Regarding the buttons, I recommend changing the first one to "Get Started," which should lead to a home/introduction/index page for each protocol. The second button should be targeted at builders, perhaps using phrases like "Start Building," "Build," or "Deploy." We can tailor the wording to each protocol, as it doesn't have to be a one-size-fits-all solution.

Another consideration to keep in mind is that the buttons currently direct users to pages that in turn redirect them back to the docs, which is counter-intuitive.

**Review by DannyS03 — APPROVED** [review]
@ashucoder9 updated the tab styling, should be good now.

I also changed the button labels; perhaps there are better ones to consider.
Feel free to modify these (and their associated links).

After that, this should be good to merge.

**Comment by DannyS03** [comment]
Adding "DNM" until @ashucoder9 takes a look and reviews the updated tab styling.

**Comment by ashucoder9** [comment]
Thanks @DannyS03 for the contribution, looks good for publishing. I'll update a few links too.

**Pull request merged**
