### PR TITLE
Reviewing docs for Nightfall Owl release

### PR DESCRIPTION
**Pull request by signorecello**
- audits nightfall docs and adds. content for owl release
- adds katex configuration and formats expressions for protocol-based docs
- general content tweaks

### CODE REVIEW

**Comment by DannyS03** [comment]
thanks @signorecello, lets leave out the package-lock.json

**Comment by druiz0992** [comment]
@DannyS03 , how do you add equations? I thought is was with `$`, but it doesn't seem to work.

**Comment by DannyS03** [comment]
@Nazeim just checking if you included katex as a plugin?

**Comment by druiz0992** [comment]
@DannyS03 @Nazeim im following documentation guide https://docusaurus.io/docs/markdown-features/math-equations to embed math, and its not rendering correctly. My guess is that katex hasn't been added?

**Comment by DannyS03** [comment]
> @DannyS03 @Nazeim im following documentation guide https://docusaurus.io/docs/markdown-features/math-equations to embed math, and its not rendering correctly. My guess is that katex hasn't been added?

@druiz0992 @Nazeim added the config for katex, please check/try now. Think some need to be updated but they are rendering now

**Comment by druiz0992** [comment]
@DannyS03 Thanks, its working

**Review by druiz0992 — APPROVED** [review]

**Comment by druiz0992** [comment]
@DannyS03 , what's the merging process? Document has been internally reviewed.

**Comment by DannyS03** [comment]
> @DannyS03 , what's the merging process? Document has been internally reviewed.

PRs will require at least one approval to merge. For changes that are more involved or specific about a technology, we'll have an SME review to fact-check, check accuracy and the approach. We'd also have 1 > reviewer for heavier changes. But the way we set up merging is that the PR needs at least one approval:)

**Review by DannyS03 — APPROVED** [review]

**Pull request merged**
