### PR TITLE
Update validator-node-system-requirements.md

### PR DESCRIPTION
**Pull request by gtelnet**
fix broken links

### CODE REVIEW

**Comment by DannyS03** [comment]
thanks @gtelnet, looks like the links are OK:

https://user-images.githubusercontent.com/25497083/189758410-9d48955b-54c5-4ded-a387-b185cb468034.mov

**Comment by gtelnet** [comment]
The links only work when you enter from the wiki.polygon.technology page, as shown in your video. Try clicking the links when you enter from https://docs.polygon.technology/docs/maintain/validate/validator-node-system-requirements/ - which is the page that a Google search page brings you to. The links I entered in the PR will work in either case, regardless of the entry page.

**Comment by DannyS03** [comment]
> The links only work when you enter from the wiki.polygon.technology page, as shown in your video. Try clicking the links when you enter from https://docs.polygon.technology/docs/maintain/validate/validator-node-system-requirements/ - which is the page that a Google search brings you to. The links I entered in the PR will work in either case, regardless of the entry page.

Ah, we recently migrated the primary DNS to be wiki.polygon.technology, where docs.polygon.technology will redirect (but seems that it is still live), so the _wiki site_ should be the only source

**Review by ashucoder9 — APPROVED** [review]
thanks @gtelnet @DannyS03. This edit seems to fix broken links present on this doc 📌

**Comment by ashucoder9** [comment]
There is something very strange about the directory structure in this section.

1. If we try to hard-code the links, that may fail in the future when we update domains or file structures.
2. If we include one level up the relative path, it breaks the links upon reload. The reason is: [https://wiki.polygon.technology/docs/maintain/validate/validator-node-system-requirements] upon reloading converts into [https://wiki.polygon.technology/docs/maintain/validate/validator-node-system-requirements/] That forward slash at the end changes the whole structure.
3. Not to mention, two-level up the path also breaks down due to similar reasons.

What can be done:
For the time being, we can hard-code the links and keep in mind not to mess with the directory structure. A better fix will be to find the fix in Docusauras itself.

Thanks @gtelnet for the contribution. @Nazeim please take a look into this.

**Comment by DannyS03** [comment]
@ashucoder9 the edit is not needed for wiki.polygon.technology and we shouldn't hardcode the page links within the markdown files. The domain for docs.polygon.technology should redirect on the client side

**Comment by DannyS03** [comment]
We have passed a request to the team to ensure redirects on the server side are correct. Based on the stale status of this PR, let's close. Please reopen if otherwise.

**Pull request closed without merging**
