### PR TITLE
[DVT-565] v0.3+ fullnode setup instructions upgrade

### PR DESCRIPTION
**Pull request by rebelArtists**
**ticket:**
https://polygon.atlassian.net/browse/DVT-565

**purpose:**
following v0.3+ releases for bor and heimdall, much simpler bootstrapping commands exist to start/sync these services, these doc upgrades reflect those changes

**tests**
e2e smoke tests starting new nodes from snapshot, decompressing, etc

### CODE REVIEW

**Comment by rebelArtists** [comment]
do not merge

**Review by brixial — APPROVED** [review]

**Comment by rebelArtists** [comment]
@DannyS03 if we could also get a preemptive review from you as these changes will be hitting prod tonight

**Comment by rebelArtists** [comment]
@maticnetwork/documentation could use a preemptive review here as technical switch is happening tomorrow, thank you

**Comment by cerberushades** [comment]
> @maticnetwork/documentation could use a preemptive review here as technical switch is happening tomorrow, thank you

@rebelArtists I'm gonna merge your PR now, but let me ask you sth: those comments on the code could have become normal text on the page, right? If you confirm, I can open a new PR later to fix that. Thank you

**Pull request merged**
