### PR TITLE
CON-221: Updated files in the develop folder

### PR DESCRIPTION
**Pull request by ashucoder9**

### CODE REVIEW

**Comment by ashucoder9** [comment]
This PR is a work in progress. Full audit will be completed by next week.

**Comment by DannyS03** [comment]
Thanks @ashucoder9! Tbh, we should split this PR up as it covers many files.

**Comment by ashucoder9** [comment]
Sure @DannyS03. Let's review and push this PR for merge first. For later iterations, I'll keep a check on the number of files.

**Comment by ashucoder9** [comment]
This PR is ready for review and merge.

**Pull request merged**
