### PR TITLE
doc: Image and link updates

### PR DESCRIPTION
**Pull request by RutvikJ77**
Reading and going through links was a hassle, hence improved the format.

### CODE REVIEW

**Review by jeffersonnnn — COMMENTED** [review]
Need to understand the motivation behind your commenting out links. Please reply when you can.

**Comment by RutvikJ77** [comment]
Sure! The reason was if we wanted to retrieve back the images there would be no link available for image retrieval (just in case imgur links go down)

**Review by RutvikJ77 — COMMENTED** [review]
Sure! The reason was if we wanted to retrieve back the images there would be no link available for image retrieval (just in case imgur links go down)

**Comment by jeffersonnnn** [comment]
Ah this makes perfect sense then. I needed a bit of context and you granted that. Since this is a pretty important part of this documentation experience, i'll take your changes and add them to a pull request to be raised against the Polygon branch. We don't raise to Master as this is hitting the road directly. Thank you very much for handling this, and please feel free to raise any changes you want to see (to the Polygon branch of course). Genuinely appreciate you and (if you're participating), Happy Hacktober!

**Comment by RutvikJ77** [comment]
Sure! Noted it. Happy Hacktober to you as well :)

**Pull request closed without merging**
