### PR TITLE
Include "Access a Full Node with Alchemy" into the Nodes sidebar

### PR DESCRIPTION
**Pull request by deric-alchemy**
As discussed with Rahat Chowdhury, Polygon DevRel.

Makes it easier for new developers to learn how to access a full node without setting one up.

See this document for full list of changes; https://docs.google.com/document/d/1t2lOd8XEW5Bdu-3YuNl5_lv4wb-MjNaycLJw7q_VwXs/edit#

### CODE REVIEW

**Comment by ashucoder9** [comment]
@deric-alchemy is this the right location for this document? I tried rewriting some stuff but it's more like a quickstart guide to Alchemy, which has not much to do in the Nodes section.

Please take a look.

**Comment by cerberushades** [comment]
@deric-alchemy thank you for your contribution, Deric. I'd avoid those icons and try to conform to our tech writing guidelines, which you can find here: https://wiki.polygon.technology/docs/contribute/writing-style

**Comment by deric-alchemy** [comment]
@ashucoder9  - intention here is to show new developers a convenient and simple alternative to running their own nodes, which many new developers may assume that they need to do in order to access the blockchain!

Intended less as a tool on "How to set up a new node", and more so "How to access information from a node with minimal effort".

Let me do a quick rewrite (particularly the intro) to make sure the intention of the article is clear to readers!

**Comment by deric-alchemy** [comment]
@ashucoder9 Removed a lot of the Alchemy language and focused the article more on providing the easiest path to accessing full nodes for new developers!

@cerberushades Removed emojis and rewrote a lot of phrasing to match tech writing guidelines!

Take a look at it whenever you're free - thank you!

**Comment by ashucoder9** [comment]
Cool @deric-alchemy, I have asked Rahat to review this doc before we push this to Polygon Wiki. Thanks 💜

**Comment by deric-alchemy** [comment]
@DannyS03 @ashucoder9 can I get an update on this?

**Pull request merged**
